# Continued learning {#post-course}

## More formatting syntax in Markdown {#post-course-markdown}

### Lists

Lists are created by adding either `- ` or `1.` to the beginning of a line
and an empty line must be at the start and end of the list.

For unnumbered lists, it looks like:

```markdown
- item 1
- item 2
- item 3
```

which gives...

- item 1
- item 2
- item 3

And numbered lists look like:

```markdown
1. item 1
2. item 2
3. item 3
```

which gives...

1. item 1
2. item 2
3. item 3

### Block quotes

Block quotes are used when you want to emphasize a block of text,
usually for quoting someone. 
You create a block quote by putting a `>` at the beginning of the line,
and as with the lists and headers, 
needs empty lines before and after the text.
So it looks like:

```markdown
> Block quote 
```

which gives...

> Block quote 

### Adding footnotes

Footnotes are added by enclosing a number or word in square brackets (`[]`)
and beginning with an uptick (`^`). It looks like:

```markdown
Footnote[^1] or this[^note].

[^1]: Footnote content
[^note]: Another footnote
```

which gives...

Footnote[^1] or this[^note].

[^1]: Footnote content
[^note]: Another footnote

### Adding links to websites

Including a link to a website in your document is done by surrounding the link text
with square brackets (`[]`) followed by the link URL in brackets (`()`).
There must not be any space between the square brackets 
and the regular brackets (it should look like `[]()`).

```markdown
[Link](https://google.com)
```

which gives...

[Link](https://google.com)

### Inserting (simple) tables

While you can insert tables using Markdown too, 
it isn't recommended to do that for complicated or large tables.
Tables are created by separating columns with `|`,
with the table header being separated by a line that looks like `|:--|`.
A simple example is:

```
|   | Fun | Serious |
|:--|----:|--------:|
| **Happy** | 1234 | 5678 |
| **Sad** | 123 | 456 |
```

which gives...

|   | Fun | Serious |
|:--|:---:|:-------:|
| **Happy** | 1234 | 5678 |
| **Sad** | 123 | 456 |

The `|---:|` or `|:---|` tell the table to left-align or right-align the values
in the column. Center-align is `|:----:|`.

So you can probably imagine,
doing this for larger or even slightly more complicated tables is not practical.
A good alternative approach is to create the table in a spreadsheet,
importing that table into R within a code chunk,
and using `knitr::kable()` to create the table after that.

## Other colour schemes in ggplot2

You can modify ggplot2 colour schemes using many other pre-defined palettes by
installing new R packages, including scientific journal colour palettes
([ggsci]) and even a Wes Anderson ([wesanderson]) or a Stubio Ghibli ([ghibli])
colour palette! 
Also check out the Data Visualization book in the [resources](resources.html)
chapter for more information and learning on visualizing data.

[ggsci]: https://nanx.me/ggsci/index.html
[wesanderson]: https://github.com/karthik/wesanderson
[ghibli]: https://ewenme.github.io/ghibli/
