---
format:
  revealjs:
    embed-resources: true
    from: markdown+emoji
    theme:
      - simple
      - theme.scss
    menu: true
    progress: true
    logo: ../images/favicon.ico
search: false
---

# Welcome to the Introductory R^3^ course!

-   :heavy_check_mark: Go to your assigned table
-   :heavy_check_mark: Introduce yourself to your group members
-   :heavy_check_mark: Accept the GitHub Organization invite
-   :heavy_check_mark: Accept the Slack channel invite

::: notes
Introduce instructors and helpers after welcoming everyone and getting
them to do this.
:::

## :raising_hand_woman: Before this course... How many knew or have heard about <u>reproducibility</u>? {.center}

::: notes
Raise your hands.
:::

## :raising_hand_woman: Before this course... How many knew or have heard about <u>open science</u>? {.center}

## :raising_hand_man: Before this course... or even <u>open access, open data, open methods/protocols, or open source</u>? {.center}

## :raising_hand_woman: How many have read a method in a paper and wondered how they <u>actually</u> did it? {.center}

::: notes
Because you are trying to do the same or similar?

And you've probably realize by now, way more is done than shown in the
"Methods".
:::

## :raising_hand_man: Have you ever received confusing code? Or maybe have written your own confusing code?

::: notes
For those that have worked with code.

I definitely have in my research career. We want to change the culture
around code by encouraging and teaching how to share code and to write
better code in general.
:::

# These highlight a problem in science... {.center}

## The scientific principle of "reproducibility" and code sharing {.smaller}

... often confused with "replicability" [@Plesser2018a]
[^introduction-1]

[^introduction-1]: Also from [American Statistical
    Association](https://www.amstat.org/asa/files/pdfs/POL-ReproducibleResearchRecommendations.pdf).

::: notes
How many could tell me the difference between replicable and
reproducible?
:::

. . .

::: columns
::: {.column width="50%"}
### Replicability

-   Same analysis + same methods + new data = same result?
-   *Independently* conducted study
-   Difficult, usually needs funding
-   Linked to the "irreproducibility crisis"[^introduction-2]
:::

::: {.column width="50%"}
### Reproducibility

-   Same data + same code = same result?
-   Should be easy right? Wrong, often just as hard
-   *Question*: If we can't even *reproduce* a studies results, how can
    we expect to replicate it?
:::
:::

[^introduction-2]: Or rather "irreplicability crisis".

## Biomedical studies almost entirely don't publish code with the published paper [@Leek2017a, @Considine2017a, @Seibold2021] {.center}

::: notes
Vast majority of papers *still* don't provide code. Except for maybe in
bioinformatics, where a bit more than half of studies do. There are lots
of reasons for this, that I talk more about tomorrow.

And this is no joke. Getting data on this is difficult, but the research
that has been done shows that almost no one is sharing their code. The
estimates range between fields in health science from zero to maybe five
percent of published studies. The only area that is doing pretty well is
bioinformatics, at about 60% of published studies.
:::

## How can we check reproducibility if no code is given? [^introduction-3]

[^introduction-3]: This is a little bit of a rhetorical question
    :stuck_out_tongue_closed_eyes:

::: notes
This is a little bit of a rhetorical question, but how might we?
:::

## Recent study: Only 25% could be *executed* without some "cleaning up" [@Trisovic2022]

-   Code taken from [Dataverse Project](https://dataverse.org/) data
    repositories
-   After some automatic cleaning, \~half could *execute*

::: notes
Recent large study on general reproducibility of projects that shared
code.

Initially only 25% of the R scripts could be *executed* (doesn't mean
results were reproduced though). After doing automatic and some manual
code cleaning, than about half could be executed. That's not bad.

Since scripts were taken from Dataverse.org, researchers who upload
their code and projects to it probably are a bit more aware and
knowledgeable about general reproducibility and coding then the average
researcher, so the results are a bit biased.
:::

## Scientific culture is not well-prepared for analytic and computation era {.center}

## These issues can be fixed by creating and nurturing a culture of openness {.center}

::: notes
All of this is because of a problem with our culture in research. We
aren't open, we don't really share, and don't often follow basic
principles of science. To fix this, we need to start creating and
nurturing a better and healthier culture. We all can be involved in
that, we all have that power to do something, even if its small thing.
:::

## Goal of this course: Start changing the culture by providing the training {.center}

# Course details

## Setup and layout {.smaller}

::: columns
::: {.column width="50%"}
-   Course is mix of:
    -   "Code-alongs" (we type and explain, you type along)
    -   Hands-on coding, discussing, and reading exercises
    -   Group project (quickly go over it)
-   All material is online (and [openly
    licensed](https://r-cubed-advanced.rostools.org/LICENSE.html))
-   [Resources
    Appendix](https://r-cubed-advanced.rostools.org/resources.html)
    -   Material for further learning
:::

::: {.column width="50%"}
-   Less about coding, more about connecting with others
    -   During lunch, try to sit beside someone you don't know
    -   Several networking activities (usually after lunch)
:::
:::

::: notes
Explain a bit more about the reading, why doing it, and that this course
in particular has a lot more of it than more advanced courses.

With the final group project, you'll be in the same group for the
course, working together on it and on the final exercises. As a team,
you'll help each other out with learning and overcoming any struggles,
with of course our help too!

I've tried to organize the groups to include a range of skills and
experiences, so there is a mix of novice and more experienced users.
:::

## Often asked: So why are we using R and why learn it? {.smaller}

::: columns
::: {.column width="50%"}
-   Open source, free
-   Very large online community
    -   Learning resources, support, help
-   Massive selection of packages
    -   Latest statistical methods
    -   Productivity tools
    -   Report writing
    -   Visualization
:::

::: {.column width="50%"}
-   Recent push to improve teaching, usability - e.g. with tidyverse,
    RStudio
-   One of best visualization tools available
-   Powerful capabilities
    -   Big Data
    -   Programming
    -   Reproducibility
:::
:::

::: notes
Regarding it being free, that means that you can take the knowledge and
skills for using R anywhere you go.
:::

## Often asked: Why are we spending time on learning things other than R? {.smaller}

Because the course is about doing *open and reproducible research*,
while using R.

::: notes
At least a few times, we get feedback in our survey about the fact we
didn't spend enough time learning R or they expected more R. That's
because we're teaching open and reproducible research, and that involves
more than just R.
:::

| Session                         | Reason                                                            |
|---------------------------------|-------------------------------------------------------------------|
| Management of R projects        | Reproducibility starts at the file level                          |
| Version control                 | Openness and reproducibility is about transparency and inspection |
| Data management and wrangling   | This one is about R :smiley_cat:                                  |
| Creating reproducible documents | Hopefully obvious :stuck_out_tongue_closed_eyes:                  |
| Data visualization              | Also about R!                                                     |

## Getting or asking for help :raising_hand_woman::raising_hand_man: {.smaller}

-   Put the sticky on your laptop to get help
-   There are lots of helpers
-   Team members, try to help out too
-   We're all learning here!
    -   This is a supportive and safe environment
    -   Remember our [Code of Conduct](conduct.html)
-   We have a [cheatsheet](../includes/cheatsheet.pdf)!

## Practice using stickies: Have you joined the GitHub Organization and the Slack group? {.center}

# Activities {.center}

## :walking::walking_woman: Who has not yet used R? {.center}

::: notes
Go to different sides of the room for "Yes" and "No"
:::

## :walking_woman::walking:Those who've used R, how do you perceive your skill in R? {.center}

::: notes
Arrange along the wall from beginner to advanced.
:::

## :raising_hand:Those who've used R or other coding tool (like Stata), have you had formal training in "coding" in it? {.center}

## :walking::walking_man::walking_woman:How do you perceive your general skill in data analysis? {.center}

## Ok, get back into your groups

# References
