# Installing the programs {#sec-install-programs}

In order to participate in the workshop, you'll need to install these
programs. You may already have some of them installed and if you did,
please make sure that they are at least the minimum versions listed
below. If not, you will need to update them.

::: {.callout-note appearance="default"}
*A note to those who have or use work laptops with restrictive
administrative privileges*: You may encounter problems installing
software due to administrative reasons (e.g. you don't have permission
to install things). Even if you have issues installing or updating the
latest version of R or RStudio, you will likely be able to continue with
the workshop as long as you have the minimum version listed above for R
and for RStudio. If you have versions of R and RStudio that are older
than that, you may need to ask your IT department to update your
software if you can't do this yourself. Unfortunately, Git is not a
commonly used software for some organizations, so you may not have it
installed and you *will* need to ask IT to install it. We *require* it
for the workshop, so please make sure to give IT enough time to be able
to install it for you prior to the workshop.
:::

::: panel-tabset
### Windows

1.  [R](https://cloud.r-project.org/bin/windows/base/): Any version
    above {{< meta versions.r >}}. If you have used R before, you can
    confirm the version by running `R.version.string` in the Console.
2.  [RStudio](https://www.rstudio.com/products/rstudio/download/#download):
    Any version above {{< meta versions.rstudio >}}. If you have
    installed it before, check the current version by going to the menu
    "Help -\> About RStudio".
3.  [Git](https://git-scm.com/download/win): Select the "Click here to
    download" link. Git is used throughout many sessions in the
    workshop. When installing, it will ask for a selecting a "Text
    Editor" and while we won't be using this in the workshop, Git needs
    to know this information so choose Notepad.
4.  [Rtools](https://cran.r-project.org/bin/windows/Rtools/): Choose the
    version that says "R-release". Rtools is needed in order to build
    some R packages. For some computers, installing Rtools can take some
    time.

### MacOS

1.  [R](https://cloud.r-project.org/bin/macosx/): Any version above
    {{< meta versions.r >}}. If you have used R before, you can confirm
    the version by running `R.version.string` in the Console. If you
    don't use [Homebrew](https://brew.sh/) to install software in MacOS,
    we strongly recommend you [install it](https://brew.sh/). It makes
    it much easier to install things, for example installing R is as
    easy as opening a Terminal and running:

    ``` {.bash filename="Terminal"}
    brew install --cask r
    ```

    If you don't use Homebrew, you can download and install R as you
    normally would by clicking the link above.

2.  [RStudio](https://www.rstudio.com/products/rstudio/download/#download):
    Any version above {{< meta versions.rstudio >}}. If you have
    installed it before, check the current version by going to the menu
    "Help -\> About RStudio". Like with installing R above with
    Homebrew, installing RStudio can be done by opening a Terminal and
    writing:

    ``` {.bash filename="Terminal"}
    brew install --cask rstudio
    ```

    If you don't use Homebrew, you can download and install RStudio as
    you normally would by clicking the link above.

3.  [Git](https://git-scm.com/download/mac): Git is used throughout many
    sessions in the workshop. With Homebrew:

    ``` {.bash filename="Terminal"}
    brew install git
    ```

    If you don't use Homebrew, you can download and install Git as you
    normally would by clicking the link above.

### Linux (Ubuntu)

1.  [R](https://cloud.r-project.org/bin/linux/ubuntu/): Any version
    above {{< meta versions.r >}}. If you have used R before, you can
    confirm the version by running `R.version.string` in the Console.

    ``` {.bash filename="Terminal"}
    sudo apt -y install r-base
    ```

2.  [RStudio](https://www.rstudio.com/products/rstudio/download/#download):
    Any version above {{< meta versions.rstudio >}}. If you have
    installed it before, check the current version by going to the menu
    "Help -\> About RStudio".

3.  [Git](https://git-scm.com/download/mac): Git is used throughout many
    sessions in the workshop.

    ``` {.bash filename="Terminal"}
    sudo apt install git
    ```
:::

All these programs are required for the workshop, even Git. Git, which
is a software program to formally manage versions of files, is used
because of it's popularity and the amount of documentation available for
it. Check out the online book [Happy Git with
R](https://happygitwithr.com/), especially the "Why Git" section, for an
understanding on why we are teaching Git. Windows users tend to have
more trouble with installing Git than macOS or Linux users. See the
section on [Installing Git for
Windows](https://happygitwithr.com/install-git.html#install-git-windows)
for help.

::: callout-tip
While not required, we *strongly* recommend installing a password
manager such as [Bitwarden](https://bitwarden.com/) as it is a much more
secure way to manage your passwords. We will be creating a temporary
GitHub "password" (called a "token") during the workshop and it makes
things much easier if you have a password manager to store it in.
:::

Once R, RStudio, and Git have been installed, open RStudio. *If you
encounter any troubles during these pre-workshop tasks*, try as best as
you can to complete the task and then let us know about the issues in
the pre-workshop survey. If you continue having problems, indicate on
the survey that you need help and we can try to book a quick video call
to fix the problem. Otherwise, you can come to the workshop 15-20
minutes earlier to get help.

If you're unable to complete the setup procedure due to unfixable
technical issues, you can use Posit Cloud (to use RStudio on the cloud)
as a final solution in order to participate in the workshop. For help
setting up Posit Cloud for this workshop, refer to the [Posit Cloud
setup guide](https://guides.rostools.org/posit-cloud).
