# Pre-reading {#sec-pre-reading}

If you haven't already, go through the workshop overview section. Read
the syllabus in @sec-syllabus, especially the part about what the
workshop will cover and what we expect you to learn at the end of it.
Then read the 'Is this for you?' section in @sec-is-this-for-you to
clarify who we've designed and built this workshop for. Lastly, read the
learning design section in @sec-learning-design to get an overview of
what types of activities we will do during the workshop as well as the
reasons for them in relation to learning.

Related to the learning design, an important component of learning is
repeated exposure to a concept or skill. We want you to read through
specific sections of the material beforehand as we've found that these
particular topics are often more difficult to grasp and understand for
beginners. Reading it beforehand will give your brain some time to start
processing the information, so that when you see it again during the
workshop, it will be easier to understand and learn. During the
workshop, you will read these sections again and we will explain them
verbally as well, to further reinforce the concepts.

Because our main learning outcome is **reproducible research**, we will
use tools like Git that is the foundation to doing reproducible
research. Without a way to easily and quickly share code, your research
*cannot* be *independently* reproducible. Using Git is the most common
way to share code.

So, please read about version control and Git in
@sec-what-is-version-control, @sec-what-is-git, and @sec-basics-of-git.
Git and version control are some of the more difficult things you will
learn in this workshop because they are fundamentally very different
ways of working on your computer than you are used to. They require
changing how you see and interact with your projects and computer in big
ways.

Lastly, briefly read through the team project work section in
@sec-project-work so you are familiar with what you will do at the end
of the workshop. You'll have time during the project work session to
read through it again, but we've found that participants prefer and want
to be aware beforehand on what is expected of them during the project
work.

::: callout-tip
To keep track of which sections to read, here is a list:

1.  @sec-syllabus
2.  @sec-is-this-for-you
3.  @sec-learning-design
4.  @sec-what-is-version-control
5.  @sec-what-is-git
6.  @sec-basics-of-git
7.  @sec-project-work
:::

## Cheatsheets

RStudio provides some great
[cheatsheets](https://posit.co/resources/cheatsheets/) that are
fantastic resources and a great reference to have readily available,
either on your computer or printed out. We suggest that you download at
least these following cheatsheets and have them available either
digitally or printed out during the workshop, especially for when you do
the exercises and team project work:

-   [RStudio IDE](https://rstudio.github.io/cheatsheets/rstudio-ide.pdf)
-   [Quarto](https://rstudio.github.io/cheatsheets/quarto.pdf)
-   [dplyr](https://rstudio.github.io/cheatsheets/data-transformation.pdf)
-   [ggplot2](https://rstudio.github.io/cheatsheets/data-visualization.pdf)
