# Networking and social activities

## Day 1 {#social-day-1 .unnumbered}

After lunch, with your group, go and walk outside or in the building and
discuss this general topic on your experiences and workflows with
tracking different versions of your files and managing changes made to
those files. If no one has any experiences or workflows to share, you
can instead brainstorm or generally discuss these topics.

-   Share an experience where you might have deleted text or code but
    thought you might have saved it somewhere in a backup or something.
    What did you do? Did you solve it? How did it make you feel?

-   Share how you manage your files and the different versions? When you
    send a paper for review to co-authors, how do you manage all the
    comments you get back? How do you save the files? When you work on a
    project, where do you save all your files related to that project?
    When you are writing documents, do you have a version for each day
    or keep working on that file?

-   Share any other experiences or ways that you manage how you work
    with files and how you make changes to them.

## Day 2 {#social-day-2 .unnumbered}

After lunch, get in your group and walk outside (or inside) while
discussing the general topic around the experiences and workflows of
working on a paper or document that had results, either alone or with
collaborators. If no one has any experiences or workflows to share, you
can instead brainstorm or generally discuss these topics.

-   Share an experience where you might have had to re-do an analysis
    and update some figures and numbers in your document. How did you
    feel while doing that? How long did it take? Was it a good
    experience or would you rather have spent that time doing something
    else?

-   Share an experience where you were working with a collaborator,
    reviewing a paper they were the lead on and it seemed like some of
    the figures or tables weren't updated based on recent discussions.
    What did you do? How did you get an updated version and how long did
    it take? How did you feel about having to rely on and wait for
    someone else to complete something after you may (or may not have)
    scheduled time to do the review of it?

-   What other experiences do you have around working with analysis
    results, including them into documents, and collaborating with
    others or at least getting feedback?
