---
format:
  rostools-theme-html:
    tbl-colwidths: [30, 70]
---

# Schedule {#sec-schedule}

The workshop is structured as a series of participatory live-coding
sessions interspersed with hands-on exercises and group work, using
either a practice dataset or some other real-world dataset. There are
some lectures given, mainly at the start and end of the workshop. The
general schedule outline is shown in the below table. This is not a
fixed schedule of the timings of each session---some may be shorter
and others may be longer. Instead, it is meant to be an approximate
guide and overview.

::: panel-tabset
## Day 1 {.unnumbered}

| Time | Session topic |
|:---|:---|
| 9:30 | {{< fa mug-hot >}} Arrival; Coffee and light breakfast |
| 10:00 | {{< fa person-chalkboard >}} [Introduction to the workshop](/sessions/introduction.qmd) |
| 10:30 | {{< fa laptop-code >}} [Setting up an R project (with a short break)](/sessions/setup-project.qmd) |
| 11:55 | {{< fa comment-dots >}} [End of session short survey]({{< meta surveys.feedback >}}) |
| 12:00 | {{< fa utensils >}} Lunch |
| 12:45 | {{< fa user-group >}} [Networking and social activity](/appendix/social.qmd#social-day-one) |
| 13:00 | {{< fa laptop-code >}} [Analytically reproducible documents](/sessions/reproducible-documents.qmd) |
| 14:25 | {{< fa comment-dots >}} [End of session short survey]({{< meta surveys.feedback >}}) |
| 14:30 | {{< fa mug-hot >}} Break with coffee and snacks |
| 14:45 | {{< fa laptop-code >}} [Version control with Git](/sessions/version-control.qmd) |
| 16:30 | {{< fa comment-dots >}} [End of session short survey]({{< meta surveys.feedback >}}) |

## Day 2 {.unnumbered}

| Time | Session topic |
|:---|:---|
| 9:00 | {{< fa laptop-code >}} [Importing data into R](/sessions/import-data.qmd) |
| 10:10 | {{< fa comment-dots >}} [End of session short survey]({{< meta surveys.feedback >}}) |
| 10:15 | {{< fa mug-hot >}} Break with coffee, team and snacks |
| 10:30 | {{< fa laptop-code >}} [Basic data visualization](/sessions/visualization.qmd) |
| 11:55 | {{< fa comment-dots >}} [End of session short survey]({{< meta surveys.feedback >}}) |
| 12:00 | {{< fa utensils >}} Lunch |
| 12:45 | {{< fa user-group >}} [Networking and social activity](/appendix/social.qmd#social-day-two) |
| 13:00 | {{< fa laptop-code >}} [Collaborating with GitHub](/sessions/github.qmd) |
| 14:25 | {{< fa comment-dots >}} [End of session short survey]({{< meta surveys.feedback >}}) |
| 14:30 | {{< fa mug-hot >}} Break with coffee and snacks |
| 14:45 | {{< fa laptop-code >}} [Data management and wrangling](/sessions/wrangling.qmd) |
| 16:30 | {{< fa comment-dots >}} [End of session short survey]({{< meta surveys.feedback >}}) |

## Day 3 {.unnumbered}

| Time | Session topic |
|:---|:---|
| 9:00 | {{< fa laptop-code >}} [Data wrangling with visualizing](/sessions/wrangling-with-visualizing.qmd) |
| 10:10 | {{< fa comment-dots >}} [End of session short survey]({{< meta surveys.feedback >}}) |
| 10:15 | {{< fa mug-hot >}} Break with coffee and snacks |
| 10:30 | {{< fa laptop-code >}} [Split, apply, and combine](/sessions/split-apply-combine.qmd) |
| 11:55 | {{< fa comment-dots >}} [End of session short survey]({{< meta surveys.feedback >}}) |
| 12:00 | {{< fa utensils >}} Lunch |
| 12:45 | {{< fa people-group >}} [Team project work (with break)](/sessions/project-work.qmd) |
| 16:00 | {{< fa people-group >}} Testing reproducibility of projects |
| 16:10 | {{< fa person-chalkboard >}} [Closing remarks](/sessions/what-next.qmd) |
| 16:30 | {{< fa comment-dots >}} [End of workshop short survey and farewell]({{< meta surveys.feedback >}}) |
:::
