palette_git_commit <- '`Ctrl-Shift-P`, then type "commit"'
palette_styler_file <- '`Ctrl-Shift-P`, then type "style file"'
palette_chunk <- '`Ctrl-Shift-P`, then type "chunk"'
palette_render <- '`Ctrl-Shift-P`, then type "render"'
keybind_knit <- '`Ctrl-Shift-K` for "Knit"'
keybind_chunk <- '`Ctrl-Alt-I` for "Insert"'
